### ISSUE TITLE
Not returning full list of results

### ISSUE THREAD

**Issue by samborambo305** [epctex-support/etsy-scraper#4]
I'm entering URLs like this:
- https://www.etsy.com/search?explicit=1&q=art+prints&ref=pagination&instant_download=false&page=4
- https://www.etsy.com/search?explicit=1&q=art+prints&ref=pagination&instant_download=false&page=5
- https://www.etsy.com/search?explicit=1&q=art+prints&ref=pagination&instant_download=false&page=6

etc. I'm expecting hundreds of results, but I'm receiving only dozens. I ran this on 10 URLs and received 133 results for example. 

Secondly, the pagination doesn't seem to work. If I provide URL:
https://www.etsy.com/search?explicit=1&q=art+prints&ref=pagination&instant_download=false

And have the end page at 10, only like 2-3 dozen results are returned.

**Comment by tugkan** [comment]
Hey @samborambo305 ! 

Thanks for reaching out. The actor is working on Residential Proxies, and it raises errors, and cannot proceed properly without it. Can you please confirm if you used the Residential Proxies? Also, if you have a Run ID, that would be very helpful for the team.

**Comment by tugkan** [comment]
Closing the issue. Feel free to reopen if needed
